version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./dockers/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - "app:app"
      - "mysql:mysql"
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-8.0
    # restart: unless-stopped
    # command: mysqld --sql_mode="ALLOW_INVALID_DATES,NO_ZERO_DATE"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verdant_sphere_kv_app
      MYSQL_USER: verdant_sphere
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test-network
    ports:
      - "3306:3306"

  app:
    container_name: blog
    build: 
      context: ./dockers/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    links: 
     - "mysql:mysql"
    networks:
      - test-network

  phpmyadmin-mysql:
    depends_on:
      - mysql
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: phpmyadmin-mysql
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
        - 8082:80
    volumes:
        - /sessions

volumes:
    mysql_data:

networks:
  test-network:
    driver: bridge
