name: CI Workflow

on:
  push:
    branches:
      - ci

jobs:
  build-job:
    name: "Build Web App"
    uses: ./.github/workflows/development.yaml
    with:
      php-version: "8.2"

  test:
    name: "Test Web App"
    needs: [build-job]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./vendor
          key: ${{ github.sha }}-php-vendor-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          composer Install

      - name: Setup Env
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Run migration and Unit Test
        run: |
          php artisan migrate:fresh --seed
          # php artisan test

  # codeScan:
  #   uses: ./.github/workflows/code-scan.yaml

  # fileScan:
  #   uses: ./.github/workflows/file-scan.yaml

  DockerBuild:
    uses: ./.github/workflows/docker-build.yaml

  # DockerScan:
  #   needs: [DockerBuild]
  #   uses: ./.github/workflows/docker-scan.yaml
