name: Development

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_ORGANIZATION:
        required: true
      SONAR_PROJECT:
        required: true

jobs:
  codeScan:
    name: "Scan Codes"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        with:
          projectBaseDir: ./
          args: Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}-Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}-Dsonar.verbose=true
