name: Main Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest

    steps:
      - name: Create docker containers
        run: docker-compose up -d mysql
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          composer Install

      - name: Setup Env
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Run Unit Test
        run: |
          php artisan migrate:fresh --seed
          php artisan test
  # build:
  #   name: Build Laravel App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: "8.2"

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Dependencies
  #       run: |
  #         composer Install

  #     - name: Setup Env
  #       run: |
  #         cp .env.ci .env

  #     - name: Build the Application
  #       run: |
  #         php artisan key:generate

  #     # - name: Tests
  #     #   uses: cloudposse/github-action-docker-compose-test-run@main
  #     #   with:
  #     #     file: ../../compose.yml
  #     #     service: app
  #     #     command: php artisan test

  #     - name: Run Unit Test
  #       run: |
  #         php artisan test
