name: CI Workflow

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      # - main
      # - dev

jobs:
  build:
    name: Build Laravel App
    uses: ./.github/workflows/build.yaml
    with:
      php-version: "8.3"
  # test:
  #   name: Test Laravel App
  #   needs: [build]
  #   uses: ./.github/workflows/test.yaml
  #   with:
  #     php-version: "8.3"
  # sonarcloud:
  #   name: Scan Security with SonarCloud
  #   needs: [build]
  #   uses: ./.github/workflows/sonarcloud.yaml
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  #     SONAR_PROJECT: ${{ secrets.SONAR_PROJECT }}
  #   with:
  #     php-version: "8.3"
  fileScan:
    name: File Security Scan with Trivy FS
    needs: [build]
    uses: ./.github/workflows/file-scan.yaml
    with:
      php-version: "8.3"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # dockerBuild:
  #   name: Create Docker Image
  #   needs: [build]
  #   uses: ./.github/workflows/docker-build.yaml
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  #     DB_USERNAME: ${{ secrets.DB_USERNAME }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  # dockerScan:
  #   name: Scan Docker Image
  #   needs: [dockerBuild]
  #   uses: ./.github/workflows/docker-scan.yaml
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}