name: Main Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      # - name: Create MySQL Docker container
      #   run: docker-compose up -d mysql

      - name: Start MySQL
        run: docker run -e MYSQL_DATABASE=verdant_sphere_kv_app MYSQL_USER=verdant_sphere MYSQL_PASSWORD=password -p 3306=3306 -d mysql-8.0

      # - name: Setup mysql
      #   uses: mirromutth/mysql-action@v1.1
      #   with:
      #     mysql database: 'verdant_sphere_kv_app' 
      #     mysql root password: 'root' 
      #     mysql user: 'verdant_sphere' 
      #     mysql password: 'password'

      - name: Install Dependencies
        run: |
          composer Install

      - name: Setup Env
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Run Unit Test
        run: |
          php artisan migrate:fresh --seed
          php artisan test
  # build:
  #   name: Build Laravel App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: "8.2"

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Dependencies
  #       run: |
  #         composer Install

  #     - name: Setup Env
  #       run: |
  #         cp .env.ci .env

  #     - name: Build the Application
  #       run: |
  #         php artisan key:generate

  #     # - name: Tests
  #     #   uses: cloudposse/github-action-docker-compose-test-run@main
  #     #   with:
  #     #     file: ../../compose.yml
  #     #     service: app
  #     #     command: php artisan test

  #     - name: Run Unit Test
  #       run: |
  #         php artisan test
