name: Main Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          composer Install

      - name: Setup Env
        run: |
          cp .env.ci .env

      - name: Build the Application
        run: |
          php artisan key:generate

      - name: Run Unit Test
        run: |
          php artisan migrate:fresh --seed
          php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push as docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./dockers/php
          file: Dockerfile
          push: true
          tags: kaungmyatsoedev/wops-laravel:latest
  
