name: "Main Workflow"
on:
  pull_request:
    branches:
      - dev

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start Running the jobs"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run second the jobs"
